services:
  step_sequencer:
    image: barciewicz/step_sequencer:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
      - 8081:8081
    tty: true